language: scala
scala:
   - 2.10.4
   - 2.11.2
jdk:
  - oraclejdk8
services:
  - postgresql
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database test;' -U postgres
  - psql test -c 'CREATE EXTENSION IF NOT EXISTS hstore;' -U postgres
  - psql test -c 'CREATE EXTENSION IF NOT EXISTS postgis;' -U postgres
