language: scala
scala:
   - 2.10.4
   - 2.11.1
jdk:
  - oraclejdk8
services:
  - postgresql
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database test;' -U postgres
  - psql -U postgres -c "create extension hstore"
  - psql -U postgres -c "create extension postgis"